name             'bde-cluster'
maintainer       'Ivan Ermilov'
maintainer_email 'iermilov@informatik.uni-leipzig.de'
license          'MIT'
description      'Installs/Configures bde-cluster'
long_description 'Installs/Configures bde-cluster'
version          '1.0.0'

depends 'java'
depends 'hadoop', '~> 2.0.9'
depends 'zookeeper-cluster'
depends 'mesos'
