name             'bde-cluster'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures bde-cluster'
long_description 'Installs/Configures bde-cluster'
version          '0.1.36'

depends 'java'
depends 'hadoop', '~> 2.0.9'
depends 'zookeeper-cluster'
depends 'mesos'
